ukf_local:
  ros__parameters:
    frequency: 50.0
    sensor_timeout: 0.1
    two_d_mode: true

    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    publish_acceleration: false

    imu0: /imu/data
    imu0_config: [
      false, false, false,   # position
      true,  true,  true,    # orientation (Mahony)
      false, false, false,   # velocity
      true,  true,  true,    # angular velocity
      true,  true,  true     # linear acceleration
    ]

    imu0_remove_gravitational_acceleration: false
