ukf_local:
  ros__parameters:
    frequency: 50.0
    two_d_mode: false

    print_diagnostics: true
    debug: true
    debug_out_file: /home/arman/debug/debug_out_file.txt

    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom

    publish_tf: true
    publish_acceleration: false

    imu0: /imu/data
    imu0_config: [
      false, false, false,   # position
      true,  true,  false,    # orientation (Mahony)
      false, false, false,   # velocity
      true,  true,  true,    # angular velocity
      false,  false,  false     # linear acceleration
    ]
    imu0_remove_gravitational_acceleration: false
