name: Run setup and colcon build for Docker
on: push
jobs:
  docker_setup_and_build_check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          docker compose build --no-cache
      - name: start and exec into container
        run: | # install moteus_msgs before arm_control is configured
          docker compose run --rm -T rover colcon build --symlink-install --packages-up-to arm_control
      - name: Cleanup
        if: always()
        run: |
          docker compose down --remove-orphans || true
      - name: Notify Discord (success)
        if: ${{ success() }}
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.DISCORD_BOT_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_BOT_WEBHOOK_TOKEN }}
          message: |
            Yipee!!! I'lll let you merge now ${{ github.actor }}. _good j*b_! || ${{ github.repository }} on `${{ github.ref_name }}`
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Notify Discord (failure)
        if: ${{ failure() }}
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.DISCORD_BOT_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_BOT_WEBHOOK_TOKEN }}
          message: |
            poo you ${{ github.actor }}! Run it through chat rq to fix your bugs  ||
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}

