name: Run setup for Docker

on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened] # prevents workflow problems

jobs:
  built-test-push:
    name: Build, Test and Push Docker Image
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
        with: # added this, might fix a bug that's taken over 3 hours to find
          submodules: recursive
      - name: build
        run: |
          docker compose build --no-cache
      - name: start and exec into container
        run: | # install moteus_msgs before arm_control is configured
          docker compose run --rm -T rover colcon build --symlink-install --packages-up-to arm_control
      - name: Cleanup
        if: always()
        run: |
          docker compose down --remove-orphans || true
      - name: Checkout source code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetches full history for better caching
          submodules: recursive

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true         # required so you can run it locally in CI
          tags: rover2025:rover

      - name: Notify Discord (success)
        if: ${{ success() }}
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.DISCORD_BOT_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_BOT_WEBHOOK_TOKEN }}
          message: |
            Yipee!!! I'lll let you merge now ${{ github.actor }}. _good j*b_! || ${{ github.repository }} on `${{ github.ref_name }}`
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Notify Discord (failure)
        if: ${{ failure() }}
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.DISCORD_BOT_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_BOT_WEBHOOK_TOKEN }}
          message: |
            poo you ${{ github.actor }}! Run it through chat rq to fix your bugs  ||
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
