name: Run setup and colcon build for Docker
on: push
jobs:
  docker_setup_and_build_check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver: docker-container
          install: true

      - name: Build multi-arch image
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --tag roverflake2:dev \
            --file Dockerfile \
            --load .
      - name: Start and exec into container
        run: |
          docker compose run --rm -T rover bash -lc \
            'rm -rf build install log && colcon build --symlink-install --packages-up-to arm_control'
      - name: Cleanup
        if: always()
        run: docker compose down --remove-orphans || true
      - name: Notify Discord (success)
        if: ${{ success() }}
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.DISCORD_BOT_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_BOT_WEBHOOK_TOKEN }}
          message: |
            Yipee!!! I'lll let you merge now ${{ github.actor }}. _good j*b_! || ${{ github.repository }} on `${{ github.ref_name }}`
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
      - name: Notify Discord (failure)
        if: ${{ failure() }}
        uses: appleboy/discord-action@v1.0.0
        with:
          webhook_id: ${{ secrets.DISCORD_BOT_WEBHOOK_ID }}
          webhook_token: ${{ secrets.DISCORD_BOT_WEBHOOK_TOKEN }}
          message: |
            poo you ${{ github.actor }}! Run it through chat rq to fix your bugs  ||
            ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
